Fix multi-line comment scanning
sebastienros/esprima-dotnet pull request #138
Opened 2020-10-31 12:07 UTC by lahma

Nullable annotations were yelling that this is a bad idea, and it was. 

Original code used to just set line and column but the real problem was that different data structures were used than in original Esprima. Changed to follow the same format for scanner structures as in JS version:

https://github.com/jquery/esprima/blob/45c9ab14d96f7f7fa88333fdd897487a8c20082f/src/scanner.ts#L15-L31

2020-10-31 14:27 UTC, lahma commented on src/Esprima/Utils/AstJson.cs
> -                        writer.Member("range");
compiler issued a warning as the member field is checked against null but the parameter is not (these use parameter event though member has been initialized)

2020-10-31 18:41 UTC, atifaziz requested changes

2020-10-31 18:41 UTC, atifaziz commented on src/Esprima/Marker.cs
> +    public class Marker
This doesn't need to be public.

2020-10-31 19:11 UTC, lahma commented on src/Esprima/Marker.cs
> +    public class Marker
Made it internal, good catch

2020-11-01 01:35 UTC, atifaziz approved these changes

2020-11-01 07:27 UTC, merged